lawliet89/biscuit

Cargo.toml
examples/claims.rs
examples/custom_header.rs
src/errors.rs
src/jws.rs
src/lib.rs

Still got to keep the crate around for its base64 methods...

Replace RustcSerialize with serde

---

examples/claims.rs
examples/custom_header.rs
src/jws.rs
src/lib.rs

Wrap RSAKeyPair in Arc

---

examples/claims.rs
src/lib.rs

Prevent serialization and deserialization of JWT::Decoded

---

Cargo.toml
examples/claims.rs
examples/custom_header.rs
src/errors.rs
src/lib.rs
src/test.rs

Implement `StringOrUri` according to JWT RFC

---

Cargo.toml
README.md
src/errors.rs
src/jws.rs
src/lib.rs

Fixes #19
Also refactor `CompactPart` traits and friends.

Remove rustc-serialize

---

examples/claims.rs
examples/custom_header.rs
src/jwa.rs
src/jwe.rs
src/jws.rs
src/lib.rs
src/serde_custom/flatten.rs

Cargo fmt code

---

src/jwe.rs
src/jws.rs

Also clarified the wording of some of the methods

Add methods to get mutable references for Compact

---

src/serde_custom/flatten.rs

TIL.
Good read: http://xion.io/post/code/rust-iter-patterns.html

Refactor to use `Iterator::partition`

---

src/jwa.rs
src/jwe.rs
src/jwk.rs
src/jws.rs
src/lib.rs
src/serde_custom/flatten.rs
src/test.rs

Based on comments on https://github.com/serde-rs/serde/issues/891

Refactor serde usage

---

README.md
doc/README.md
doc/supported.md
src/lib.rs

~**Don't merge yet -- not done**~
Fixes #57

Document Supported features

---

Cargo.toml
src/lib.rs

Not going to use the provided serde implementation because it will be really painful to work around `Option<...>`.

Upgrade to Chrono 0.4.0

---

src/jwk.rs

I needed to search my JWKSet for a key id so I figured this functionality would be useful upstream.
Comes with tests!
Resubmitting this on a branch so I don't gunk it up with other work.

Add a find method on JWKSet to find a JWK by kid

---

Cargo.toml
src/errors.rs
src/lib.rs

Integrate failure crate

---

Cargo.toml
src/errors.rs
src/lib.rs

Reverts lawliet89/biscuit#101
Wait for `failure` to be stable first.

Revert "Integrate failure crate"

---

CHANGELOG.md
Cargo.toml
README.md
fuzz/fuzz_targets/fuzz_decryption.rs
src/jwa.rs
src/jwe.rs
src/jwk.rs
src/lib.rs

Fixes https://github.com/lawliet89/biscuit/issues/118

Fix spelling for all `Octect` to `Octet`

---

Cargo.toml
src/jwa.rs
src/lib.rs

- Geal/nom#1058 (especially on async-std issue)
- rust-lang-nursery/lazy-static.rs#111
- rust-lang/rfcs#2788 (ongoing RFC)

Replace lazy_static with once_cell

---

src/errors.rs
src/jws.rs

Includes #128 
Fixes #127
I was unable to update the branch in #128. So opening a new PR.

Allow for optional `alg` in JWK

---

src/jws.rs

Fixes https://github.com/lawliet89/biscuit/issues/159

Derive `Clone` for `jws::Secret`

---

src/lib.rs

This should fix the CI
(Will rebase my other PRs on top of this)

Rustc nightly lints

---

src/jwk.rs

Fixes https://github.com/lawliet89/biscuit/issues/203

Derive Clone for `JWKSet`

---

src/jwa.rs
src/jwe.rs
src/jwk.rs
src/jws/compact.rs
src/test.rs

Remove needless borrows

---

Cargo.lock
Cargo.toml
src/jwa.rs
src/jwe.rs
src/jwk.rs
src/jws.rs
src/lib.rs
src/serde_custom/base64_url_uint.rs
src/serde_custom/option_base64_url_uint.rs

A small change, removing a few dependencies.

Replace the num dependency with more specific parts

---

.github/dependabot.yml
.github/workflows/rust.yml
Cargo.lock
Cargo.toml
src/helpers/presence.rs
src/helpers/validation.rs
src/jwa.rs
src/jwe.rs
src/jwk.rs
src/jws/flattened.rs
src/lib.rs

[Breaking] Fix build errors and bump MSRV

---

src/errors.rs
src/jwa.rs
src/jwk.rs

This pull request fixes some typos.

Fix a few typos

---

Cargo.lock
Cargo.toml
src/jwa.rs
src/jws.rs
src/jws/flattened.rs
src/lib.rs

Update ring version to 0.17.5
